import type { Event, TeamMember } from './types';

export const events: Event[] = [
  {
    id: 1,
    slug: 'diwali-festival-of-lights-2024',
    name: 'Diwali Festival of Lights 2024',
    date: 'November 2, 2024',
    time: '5:00 PM - 10:00 PM',
    location: 'Phoenix Temple Grounds',
    image: 'https://placehold.co/600x400.png',
    description: 'Celebrate the festival of lights with fireworks, food, and cultural performances.',
    fullDescription: 'Join us for our grandest celebration of the year! The Diwali Festival of Lights will feature a spectacular fireworks display, dozens of food stalls with authentic Indian cuisine, live music, classical and folk dance performances, and activities for the whole family. It is a night of joy, community, and light over darkness.',
    category: 'Cultural',
  },
  {
    id: 2,
    slug: 'holi-festival-of-colors-2025',
    name: 'Holi Festival of Colors 2025',
    date: 'March 14, 2025',
    time: '11:00 AM - 4:00 PM',
    location: 'Scottsdale Civic Center Park',
    image: 'https://placehold.co/600x400.png',
    description: 'Join us for a vibrant celebration of Holi with colors, music, and dance.',
    fullDescription: 'Experience the most colorful event in Arizona! Our Holi Festival brings together people from all walks of life to celebrate the arrival of spring. Enjoy throwing organic colored powders, dancing to the beats of a live DJ, delicious food trucks, and a day of fun and friendship.',
    category: 'Cultural',
  },
  {
    id: 3,
    slug: 'arizona-india-food-fair-2024',
    name: 'Arizona India Food Fair 2024',
    date: 'October 12, 2024',
    time: '12:00 PM - 8:00 PM',
    location: 'Chandler Community Center',
    image: 'https://placehold.co/600x400.png',
    description: 'A culinary journey through the diverse flavors of India, from street food to fine dining.',
    fullDescription: 'Calling all foodies! The Arizona India Food Fair is your passport to the incredible culinary diversity of India. Sample dishes from every region, watch live cooking demonstrations from master chefs, and enjoy a day filled with delicious food, music, and cultural showcases.',
    category: 'Food',
  },
  {
    id: 4,
    slug: 'sangeet-sandhya-an-evening-of-music-2024',
    name: 'Sangeet Sandhya: An Evening of Music',
    date: 'September 21, 2024',
    time: '7:00 PM - 9:30 PM',
    location: 'Mesa Arts Center',
    image: 'https://placehold.co/600x400.png',
    description: 'An enchanting evening featuring classical Indian music and contemporary fusion.',
    fullDescription: 'Sangeet Sandhya is a celebration of India\'s rich musical heritage. This concert will feature performances by renowned classical musicians, as well as exciting fusion pieces that blend traditional Indian sounds with contemporary genres. A perfect evening for music lovers.',
    category: 'Music',
  },
  {
    id: 5,
    slug: 'nritya-shakti-dance-showcase-2024',
    name: 'Nritya Shakti: Dance Showcase 2024',
    date: 'December 7, 2024',
    time: '6:00 PM - 8:30 PM',
    location: 'Tempe Center for the Arts',
    image: 'https://placehold.co/600x400.png',
    description: 'A spectacular showcase of Indian dance forms, from Bharatanatyam to Bollywood.',
    fullDescription: 'Prepare to be mesmerized by Nritya Shakti, our annual dance showcase. This event highlights the grace, power, and beauty of Indian dance, featuring talented local artists performing everything from classical forms like Kathak and Bharatanatyam to high-energy Bollywood routines.',
    category: 'Dance',
  },
  {
    id: 6,
    slug: 'independence-day-celebration-2025',
    name: 'Independence Day Celebration 2025',
    date: 'August 15, 2025',
    time: '10:00 AM - 2:00 PM',
    location: 'Arizona State Capitol Lawn',
    image: 'https://placehold.co/600x400.png',
    description: 'Celebrate India\'s Independence Day with patriotic songs, flag hoisting, and cultural programs.',
    fullDescription: 'Join the Indian community of Arizona as we celebrate India\'s Independence Day. The event will feature a flag hoisting ceremony, singing of the national anthem, patriotic performances, and speeches from community leaders. A day to celebrate our freedom and heritage.',
    category: 'Cultural',
  }
];

export const teamMembers: TeamMember[] = [
  {
    id: 1,
    name: 'Priya Sharma',
    role: 'President & Co-Founder',
    image: 'https://placehold.co/400x400.png',
    bio: 'Priya has been a community leader for over 15 years, with a passion for cultural preservation and youth engagement. She is the driving force behind our largest festivals.',
  },
  {
    id: 2,
    name: 'Raj Singh',
    role: 'Vice President',
    image: 'https://placehold.co/400x400.png',
    bio: 'Raj brings his expertise in event management and logistics to the team. He ensures every event runs smoothly and safely for all attendees.',
  },
  {
    id: 3,
    name: 'Anika Patel',
    role: 'Treasurer',
    image: 'https://placehold.co/400x400.png',
    bio: 'Anika manages the financial health of the organization, overseeing budgeting, sponsorships, and donations with meticulous care.',
  },
  {
    id: 4,
    name: 'Sameer Gupta',
    role: 'Community Outreach Lead',
    image: 'https://placehold.co/400x400.png',
    bio: 'Sameer is dedicated to building bridges within the community. He leads our volunteer programs and charitable initiatives.',
  },
];
